language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - nightly

sudo: false
matrix:
  fast_finish: true

before_script:
   - travis_retry composer self-update
   - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit